version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    hostname: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: [ 'postgres', '-c', 'wal_level=logical' ]


  mysql:
    image: mysql:latest
    restart: always
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3306:3306'


  mongodb:
    image: mongo:latest
    restart: always
    hostname: mongodb
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"


  redis:
    image: redis:latest
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"