scrape_configs:
  - job_name: 'otel-collector-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector-collector:8889']
      - targets: ['otel-collector-collector:8888']
