version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    hostname: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: [ 'postgres', '-c', 'wal_level=logical' ]