version: '3.9'

services:
  mysql:
    image: mysql:latest
    restart: always
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3306:3306'
    networks:
      - system_default


networks:
  system_default:
    name: system_default
    driver: bridge