version: '3.9'

services:
  redis:
    image: redis:latest
    hostname: redis
    container_name: redis
    ports:
      - '6379:6379'
    restart: always
    networks:
      - system_default


networks:
  system_default:
    name: system_default
    driver: bridge