version: '3.9'

services:
  nats:
    image: nats:latest
    hostname: nats
    container_name: nats
    ports:
      - '4222:4222'
      - '8222:8222'
    networks:
      - system_default


networks:
  system_default:
    name: system_default
    driver: bridge